version: "3.9"

services:
  api:
    build: ./api
    image: flaviogf/conduit-api
    ports:
      - 3000:3000
    environment:
      CONDUIT_DATABASE: "host=db user=postgres password=postgres dbname=conduit sslmode=disable"
      CONDUIT_KEY: "calopsita"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "conduit"
    volumes:
      - ./api/internal/database:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  data:
