version: "3.9"

services:
  api:
    build: ./api
    image: flaviogf/conduit-api
    environment: 
      CONDUIT_DB: "host=db user=postgres password=postgres dbname=conduit sslmode=disable"
    ports:
      - 3000:80
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: conduit
    volumes:
      - ./api/internal/database:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  data:
