CREATE TABLE Users
(
	Id CHAR(36) PRIMARY KEY NOT NULL,
	UserName NVARCHAR(255) NOT NULL,
	Email NVARCHAR(255) NOT NULL,
	Bio NVARCHAR(255) NOT NULL,
	Avatar NVARCHAR(255) NOT NULL,
	PasswordHash NVARCHAR(255) NOT NULL
)
