CREATE Table Articles
(
	Id CHAR(36) PRIMARY KEY NOT NULL,
	Title NVARCHAR(255) NOT NULL,
	Description NVARCHAR(255) NOT NULL,
	Body NVARCHAR(MAX) NOT NULL,
	AuthorId CHAR(36) NOT NULL FOREIGN KEY REFERENCES Users (Id)
)
